title: Adrian Willi
email: you@example.com
url: "https://adrian-willi.github.io"
baseurl: ""   # If hosting at root, leave empty
description: "A professional CV and blog website by Adrian Willi."
navbar:
  - title: "Home"
    path: "/"
  - title: "About"
    path: "/about"
  - title: "Research CV"
    path: "/"
  - title: "Blog"
    path: "/blog/"
theme: minima
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: page
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# For blog excerpts
excerpt_separator: <!--more-->
